import {
  Initialize,
  Finding,
  HandleAlert,
  AlertEvent,
  FindingSeverity,
  FindingType,
} from "forta-agent";

import { BOT_ID, TARGET_CONTRACT } from "./constants";
const initialize: Initialize = async () => {
  // subscribing to alerts ASSET-DRAINED generated by bot BOT_ID on Ethereum chain
  return {
    alertConfig: {
      subscriptions: [
        {
          botId: BOT_ID,
          chainId: 1,
          alertIds: ["ASSET-DRAINED"],
        },
      ],
    },
  };
};

const handleAlert: HandleAlert = async (alertEvent: AlertEvent) => {
  const findings: Finding[] = [];
  if (alertEvent.alert.metadata?.contract == TARGET_CONTRACT) {
    findings.push(
      Finding.fromObject({
        name: "Assets drained",
        description: `Assets drained for contract ${TARGET_CONTRACT}`,
        alertId: "ASSET-DRAINED-1",
        severity: FindingSeverity.High,
        type: FindingType.Suspicious,
        metadata: {
          block: alertEvent.alert.metadata.blockNumber,
        },
      })
    );
  }
  return findings;
};

export default {
  initialize,
  handleAlert,
};
